export enum Powers {
    GERMANY = "GERMANY",
    SOVIET_UNION = "SOVIET_UNION",
    COMMUNIST_CHINA = "COMMUNIST_CHINA",
    JAPAN = "JAPAN",
    UK_WEST = "UK_WEST",
    UK_EAST = "UK_EAST",
    ANZAC = "ANZAC",
    FRANCE = "FRANCE",
    ITALY = "ITALY",
    USA = "USA",
    NATIONALIST_CHINA = "NATIONALIST_CHINA",
}
